CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Doctors" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Crm" character varying(10) NOT NULL,
    "Specialty" character varying(100) NOT NULL,
    "Password" text NOT NULL,
    "Profile" integer NOT NULL,
    CONSTRAINT "PK_Doctors" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Doctors_Crm" ON "Doctors" ("Crm");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250205005132_InitialDatabase', '9.0.1');

ALTER TABLE "Doctors" ALTER COLUMN "Profile" TYPE smallint;

CREATE TABLE "Patients" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Email" character varying(200) NOT NULL,
    "Cpf" character varying(11) NOT NULL,
    "Profile" smallint NOT NULL,
    "Password" text NOT NULL,
    CONSTRAINT "PK_Patients" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Patients_Cpf" ON "Patients" ("Cpf");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250205113318_AddPatientTable', '9.0.1');

COMMIT;

