CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Doctors" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Crm" character varying(10) NOT NULL,
    "Specialty" character varying(100) NOT NULL,
    "AppointmentValue" numeric(10,2) NOT NULL,
    "Password" text NOT NULL,
    "Profile" smallint NOT NULL,
    CONSTRAINT "PK_Doctors" PRIMARY KEY ("Id")
);

CREATE TABLE "Patients" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "Email" character varying(200) NOT NULL,
    "Cpf" character varying(11) NOT NULL,
    "Profile" smallint NOT NULL,
    "Password" text NOT NULL,
    CONSTRAINT "PK_Patients" PRIMARY KEY ("Id")
);

CREATE TABLE "AppointmentSlots" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "DoctorId" bigint NOT NULL,
    "AvailableDate" timestamp without time zone NOT NULL,
    "AvailableTime" interval NOT NULL,
    CONSTRAINT "PK_AppointmentSlots" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AppointmentSlots_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Appointments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "DoctorId" bigint NOT NULL,
    "PatientId" bigint NOT NULL,
    "AppointmentSlotId" bigint NOT NULL,
    "Status" character varying(50) NOT NULL,
    "Justification" character varying(500),
    CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Appointments_AppointmentSlots_AppointmentSlotId" FOREIGN KEY ("AppointmentSlotId") REFERENCES "AppointmentSlots" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Appointments_Doctors_DoctorId" FOREIGN KEY ("DoctorId") REFERENCES "Doctors" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Appointments_Patients_PatientId" FOREIGN KEY ("PatientId") REFERENCES "Patients" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Appointments_AppointmentSlotId" ON "Appointments" ("AppointmentSlotId");

CREATE INDEX "IX_Appointments_DoctorId" ON "Appointments" ("DoctorId");

CREATE INDEX "IX_Appointments_PatientId" ON "Appointments" ("PatientId");

CREATE INDEX "IX_AppointmentSlots_DoctorId" ON "AppointmentSlots" ("DoctorId");

CREATE UNIQUE INDEX "IX_Doctors_Crm" ON "Doctors" ("Crm");

CREATE UNIQUE INDEX "IX_Patients_Cpf" ON "Patients" ("Cpf");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250207134948_InitDatabase', '9.0.1');

COMMIT;

